name: Agendador de amor

on:
  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:
  
  
jobs:
  executar-amor:
    runs-on: ubuntu-latest
    steps:
    - name: Checar c√≥digo
      uses: actions/checkout@v2
    - name: Instalando streamlink e selenium
      run: |
          pip install --user --upgrade streamlink
          pip install --user --upgrade selenium
          pip install yt-dlp
          pip install pytube
          pip install youtube-dl
          pip install requests
          pip install beautifulsoup4
          pip install fastapi
          pip install uvicorn
          pip install schedule
          
    - name: Executar script
      run: python amor.py
      
    - name: Fazer push do arquivo YAML
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add agendador-de-amor.yml
          git commit -m "Atualizar agendador-de-amor.yml"
          git push origin HEAD:main
